- name: Install and then remove packages
  hosts: all
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - docker.io
          - nginx
          - python3
        state: present
        update_cache: yes

    - name: Purge the packages
      ansible.builtin.apt:
        name:
          - docker.io
          - nginx
          - python3
        state: absent
        purge: yes  # Removes config files too

    - name: Autoremove unnecessary dependencies
      ansible.builtin.apt:
        autoremove: yes
