- name: Fix Package Issues and Install Packages
  hosts: all
  become: yes # Use privilege escalation (sudo)
  tasks:
    - name: Ensure package cache is updated
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Ensure required repositories are enabled (universe, multiverse)
      ansible.builtin.command: add-apt-repository -y {{ item }}
      with_items:
        - universe
        - multiverse
      register: add_repo_result
      changed_when: add_repo_result.rc == 0
      ignore_errors: yes

    - name: Refresh package lists after repository changes
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - docker.io
          - nginx
        state: present

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - docker.io
          - nginx
        state: absent
